name: SimpleCommandTimer
main: com.siberanka.simplecommantimer.SimpleCommandTimerPlugin
version: 1.0.2
api-version: 1.16
author: siberanka
folia-supported: true
commands:
  sctimer:
    description: Reloads config or manually triggers an entry
    usage: /sctimer reload | /sctimer trigger <entry_id>
permissions:
  sctimer.admin:
    default: op

