name: SimpleCommandTimer
main: com.siberanka.simplecommantimer.SimpleCommandTimerPlugin
version: 1.0.0
api-version: 1.16
author: siberanka
folia-supported: true
commands:
  sctimer:
    description: Reloads the SimpleCommandTimer configuration
    usage: /sctimer reload
permissions:
  sctimer.admin:
    default: op
